---
title: "Mukilteo Salmon Shed Conductivty Characterizations (HOBOlogger history)"
output:
 html_document:
    df_print: paged
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: true
    theme: journal
    highlight: zenburn
    smart: false

---

# Libraries
```{r 0.0 Libraries , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
##Libraries
#********************************* 
library(here)
library(data.table)
library(stringr)
library(tidyverse)
library(plyr)
library(nlme)
library(tidyr)
library(dbplyr)
library(dplyr)
library(purrr)
library(wql)
library(lubridate)
library(tibbletime)
library(arsenal)
library(compareDF)
#for graphing
library(ggplot2)
library(ggfortify)
library(stringr)
library(nlme)
library(RColorBrewer)
library(patchwork)
#statistical analysis
library(gdata)
library(rsq)
library(doBy)
#Rnotebooks 
library(gridExtra)
library(kableExtra)

```



# 1.) Setting Working Directory
```{r 1.) Setting Working Directory, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE }
#*********************************
## 1.) Setting Working Directory
#*********************************

#set working directory to the correct folder
setwd("/Users/katherinerovinski/GIT/NWFSC.MUK_DGNjuvenile_ConductivityHOBOloggerHistory")

```


# 2.) Creating Dataframe & Spooling
```{r  }
#*********************************
## 2.) Spooling Data into one CSV 
#*********************************
#Combining multiple CSV files into 1 document. Original input files from individual 

#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |
## 2.1 Create a list of files 
filesCNDCT <- list.files(pattern = ".csv")
print(filesCNDCT)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

## 2.2 Create a temporary place for files 
tempCNDCT <- lapply(filesCNDCT, fread, sep= ",")
print(tempCNDCT)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

## 2.3 Create a new vector for Moats data logs 
# "M01thruM13Moatslog_data" via rbind
dHOBOloggerCNDCT <- rbindlist(tempCNDCT, fill = TRUE)
print(dHOBOloggerCNDCT)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

```

# 2.1) Cleaning up the dataframe
```{r}

# dHOBOloggerCNDCT<- dHOBOloggerCNDCT[-1,]

```






```{r}
#**************E*N*D*************# 
#*********************************
## END OF SCRIPT | END OF DOCUMENT 
#*********************************
```


## END OF SCRIPT | END OF DOCUMENT

